Update versioning.yml

diff --git a/.github/workflows/versioning.yml b/.github/workflows/versioning.yml
--- a/.github/workflows/versioning.yml
+++ b/.github/workflows/versioning.yml
@@ -1,34 +1,31 @@
-name: Version Management
-
-on:
-  push:
-    branches:
-      - main
-
-jobs:
-  version:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Increment version
-        id: increment_version
-        run: |
-          if [ ! -f Version.txt ]; then
-            echo "Version.txt not found! Exiting."
-            exit 1
-          fi
-          current_version=$(cat Version.txt)
-          IFS='.' read -r major minor patch <<< "$current_version"
-          patch=$((patch + 1))
-          new_version="$major.$minor.$patch"
-          echo $new_version > Version.txt
-          git config --local user.name "github-actions"
-          git config --local user.email "actions@github.com"
-          git add Version.txt
-          git commit -m "Increment version to $new_version" || echo "No changes to commit"
-          git tag "v$new_version"
-          git push "https://JohanGalindo08:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/JohanGalindo08/DevOps_Grupo_1.git" main --tags
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+- name: Increment version
+  id: increment_version
+  run: |
+    if [ ! -f Version.txt ]; then
+      echo "Version.txt not found! Exiting."
+      exit 1
+    fi
+    current_version=$(cat Version.txt)
+    IFS='.' read -r major minor patch <<< "$current_version"
+    patch=$((patch + 1))
+    new_version="$major.$minor.$patch"
+    
+    # Verificar si la etiqueta ya existe
+    if git ls-remote --tags https://github.com/JohanGalindo08/DevOps_Grupo_1.git | grep "refs/tags/v$new_version" ; then
+      echo "Tag v$new_version already exists. Incrementing patch version."
+      patch=$((patch + 1))
+      new_version="$major.$minor.$patch"
+    fi
+    
+    echo $new_version > Version.txt
+    git config --local user.name "github-actions"
+    git config --local user.email "actions@github.com"
+    git checkout -b increment-version
+    git add Version.txt
+    git commit -m "Increment version to $new_version" || echo "No changes to commit"
+    
+    # Eliminar la etiqueta remota si ya existe
+    git push --delete origin v$new_version || echo "Tag v$new_version does not exist."
+    
+    git tag "v$new_version"
+    git push "https://JohanGalindo08:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/JohanGalindo08/DevOps_Grupo_1.git" main --tags
